### ISSUE TITLE
Squash Git history into a single commit

### ISSUE THREAD

**Issue by andydavies92** [Stack-in-a-box/siab-search#1]
# Overview

This codebase will eventually become distinct-enough from the original plugin repository that the previous history will be largely irrelevant. In addition to this, this fork is never intended to be merged back into the original repo so it's fine to squash history. Doing so will help keep the codebase tidy going forward so that the focus remains on the new changes. It should also reduce the total size of the repository to speed-up cloning.

The `Tipue-Search` history is only 13 commits deep as they used commits as an abstraction for releases, containing a multitude of changes within each one. As such, that should mean the rebase should be a largely trivial exercise.

# Tasks

- [x] Delete [all old releases](https://www.github.com/Stack-in-a-box/siab-search/releases) that were included in the fork.
- [ ] Squash all commits down to a single one.
- [ ] Wipe the readme in the root so that it just contains the project name.

# Resources

Use this Stack Overflow answer as reference on how to perform the history squashing:
https://stackoverflow.com/questions/1657017/how-to-squash-all-git-commits-into-one/9254257#9254257
