### ISSUE TITLE
Correct indentation and tidy-up other whitespace issues

### ISSUE THREAD

**Issue by andydavies92** [Stack-in-a-box/siab-search#3]
# Overview

~While there aren't any occurrences of tabs used for indentation in this codebase (which makes a nice change)~ (**edit:** found some...), there are instances of 2 spaces used as indentation units instead of the more-standard 4 and, bizarrely, 5 spaces instead of 4 too. We should change these to be consistent so that all indentation is formed of units of four space characters. In addition, since find-and-replace operations will affect areas where variable assignments and the like have been manually aligned with additional spaces, we should remove these extra spaces and just use a single space in these cases. Also keep an eye out for other whitespace issues like lines with trailing whitespace and multiple consecutive newlines!

**Edit:** It makes more sense to just use an automatic document formatter in a text editor to fix all issues at once (for the most part), so should just correct all indentation issues in one go.

# Tasks

- [ ] Change units of 5 spaces to 4.
- [ ] Change units of 2 spaces to 4.
- [ ] Remove whitespace used for custom alignment.
- [ ] Remove trailing whitespace.
- [ ] Remove instances of multiple newlines.
- [ ] Correct improper indentation and spacing.
