### ISSUE TITLE
Flatten filesystem and remove unnecessary files

### ISSUE THREAD

**Issue by andydavies92** [Stack-in-a-box/siab-search#4]
# Overview

There are a bunch of duplicated files in the repository that are used for the demo application but these are unnecessary so they should be removed. The codebase is also simple enough that it doesn't warrant being "organised" into directories either so the structure should be flattened so that all source exists in the root directory of the repository. In addition, there are a bunch of macOS-specific files present which should be removed, specifically `.DS_Store` files.

# Tasks

- [x] Remove macOS-specific files.
- [x] Remove other unnecessary files.
- [x] Remove duplicate source files.
- [x] Flatten directory structure.
