### ISSUE TITLE
Use ES6 string interpolation instead of string concatenation where appropriate

### ISSUE THREAD

**Issue by andydavies92** [Stack-in-a-box/siab-search#5]
# Overview

The majority of this application relies on string-bashing raw HTML to render results; most of this is done using old-style string concatenation, e.g. `'<element>' + content + '</element>'` as that was the only option available in ES5. Since this plugin is going to be targeting modern, evergreen browsers, it's safe to upgrade to use ES6 features. As such, that means the above becomes much more readable:

```javascript
`<element>${content}</element>`
```

While this example may be somewhat contrived, the older style quickly becomes a lot harder to mentally parse as the statements get more complex, so this is a necessary step for being able to effectively and efficiently reverse-engineer this code...

Throughout this code, all string literals are represented with single quotes, for example `'This is a string literal...'`, whereas we should ideally be using double quotes for extra visible distinction, i.e. `"This is a string literal..."`. As part of this issue, convert any simple string literals that don't require string interpolation to use double quotes instead of single ones (except when the content of the string requires double quote characters, in which case backticks should be used to avoid individual character escaping). Also, remove unnecessary comments and continue to improve code layout as part of this work.

# Tasks

- [x] Upgrade to ES6 string interpolation for string-bashing operations.
- [x] Replace single quotes with double quotes for simple string literals.
- [x] Use backticks for string literals where double quotes need to be escaped.

# Resources

Use this article as reference for ES6 "template strings", more commonly known in other languages as "string interpolation":
https://developers.google.com/web/updates/2015/01/ES6-Template-Strings
