### ISSUE TITLE
Factor elements from tipuesearch_set.js into their own files

### ISSUE THREAD

**Issue by andydavies92** [Stack-in-a-box/siab-search#6]
# Overview

One of the support files for Tipue Search, `tipuesearch_set.js` contains a combination of different elements which are referenced by the main application. These don't necessarily belong in a file together so they should be either inlined or split-out into their own file. Rename any variables and tweak data structures as appropriate to make the code more readable.

# Tasks

- [x] Pull stop words out to their own file.
- [x] Pull replace words out to their own file.
- [x] Pull weightings out to their own file.
- [x] Pull stem words out to their own file.
- [x] Pull related searches out to their own file.
- [x] Pull start timer out to its own file.
- [x] Inline strings to be displayed to the user.
